name: Test

on:
  push:
    branches:
      - main
      - master
  pull_request:

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync

      - name: Lint package
        run: uv run poe lint

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    name: Python ${{ matrix.python-version }}

    services:
      rabbitmq:
        image: rabbitmq:3.12
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync

      - name: Test package
        run: uv run poe test
        env:
          PYTEST_RABBITMQ_HOST: 127.0.0.1
          PYTEST_RABBITMQ_PORT: ${{ job.services.rabbitmq.ports['5672'] }}

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: reports/coverage.xml
